
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ItemType
    {
        /// <summary>
        /// 一级经验球
        /// </summary>
        ExpBall1 = 0,
    }

} 

