
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class SActorAttribute
{
    private readonly System.Collections.Generic.Dictionary<int, SActor2Attribute> _dataMap;
    private readonly System.Collections.Generic.List<SActor2Attribute> _dataList;
    
    public SActorAttribute(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SActor2Attribute>();
        _dataList = new System.Collections.Generic.List<SActor2Attribute>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SActor2Attribute _v;
            _v = SActor2Attribute.DeserializeSActor2Attribute(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SActor2Attribute> DataMap => _dataMap;
    public System.Collections.Generic.List<SActor2Attribute> DataList => _dataList;

    public SActor2Attribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SActor2Attribute Get(int key) => _dataMap[key];
    public SActor2Attribute this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

