
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class SCharacter2 : Luban.BeanBase
{
    public SCharacter2(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CharacterType = (TCharacterID)_buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static SCharacter2 DeserializeSCharacter2(ByteBuf _buf)
    {
        return new SCharacter2(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 人物
    /// </summary>
    public readonly TCharacterID CharacterType;
    /// <summary>
    /// 技能分类
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 120814300;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterType:" + CharacterType + ","
        + "name:" + Name + ","
        + "}";
    }
}

}
