
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class SCharacter : Luban.BeanBase
{
    public SCharacter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CharacterType = (TCharacterType)_buf.ReadInt();
        Name = _buf.ReadString();
        Hp = _buf.ReadFloat();
        Atk = _buf.ReadFloat();
        Def = _buf.ReadFloat();
        Speed = _buf.ReadFloat();
    }

    public static SCharacter DeserializeSCharacter(ByteBuf _buf)
    {
        return new SCharacter(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 人物
    /// </summary>
    public readonly TCharacterType CharacterType;
    /// <summary>
    /// 人物名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly float Atk;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly float Def;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
   
    public const int __ID__ = 142444566;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterType:" + CharacterType + ","
        + "name:" + Name + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "def:" + Def + ","
        + "speed:" + Speed + ","
        + "}";
    }
}

}
