
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class SItem
{
    private readonly System.Collections.Generic.Dictionary<int, SAnim2Name> _dataMap;
    private readonly System.Collections.Generic.List<SAnim2Name> _dataList;
    
    public SItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SAnim2Name>();
        _dataList = new System.Collections.Generic.List<SAnim2Name>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SAnim2Name _v;
            _v = SAnim2Name.DeserializeSAnim2Name(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SAnim2Name> DataMap => _dataMap;
    public System.Collections.Generic.List<SAnim2Name> DataList => _dataList;

    public SAnim2Name GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SAnim2Name Get(int key) => _dataMap[key];
    public SAnim2Name this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

