
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum SkillKind
    {
        /// <summary>
        /// 基础
        /// </summary>
        Base = 0,
        /// <summary>
        /// 升级
        /// </summary>
        Upgrade = 1,
    }

} 

