
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum SkillType
    {
        /// <summary>
        /// 大剑
        /// </summary>
        Sword = 0,
        /// <summary>
        /// 法杖
        /// </summary>
        Staff = 1,
        /// <summary>
        /// 弓
        /// </summary>
        Bow = 2,
    }

} 

