
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TAnim TAnim {get; }
    public TSkill TSkill {get; }
    public TCharacter TCharacter {get; }
    public TEnemy TEnemy {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TAnim = new TAnim(loader("tanim"));
        TSkill = new TSkill(loader("tskill"));
        TCharacter = new TCharacter(loader("tcharacter"));
        TEnemy = new TEnemy(loader("tenemy"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TAnim.ResolveRef(this);
        TSkill.ResolveRef(this);
        TCharacter.ResolveRef(this);
        TEnemy.ResolveRef(this);
    }
}

}
