
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public SItem SItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SItem = new SItem(loader("sitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SItem.ResolveRef(this);
    }
}

}
