
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public SAnimName SAnimName {get; }
    public SActorAttribute SActorAttribute {get; }
    public SSkillAttribute SSkillAttribute {get; }
    public SCharacter SCharacter {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SAnimName = new SAnimName(loader("sanimname"));
        SActorAttribute = new SActorAttribute(loader("sactorattribute"));
        SSkillAttribute = new SSkillAttribute(loader("sskillattribute"));
        SCharacter = new SCharacter(loader("scharacter"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SAnimName.ResolveRef(this);
        SActorAttribute.ResolveRef(this);
        SSkillAttribute.ResolveRef(this);
        SCharacter.ResolveRef(this);
    }
}

}
