
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TCharacter
{
    private readonly System.Collections.Generic.Dictionary<int, SCharacter> _dataMap;
    private readonly System.Collections.Generic.List<SCharacter> _dataList;
    
    public TCharacter(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SCharacter>();
        _dataList = new System.Collections.Generic.List<SCharacter>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SCharacter _v;
            _v = SCharacter.DeserializeSCharacter(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SCharacter> DataMap => _dataMap;
    public System.Collections.Generic.List<SCharacter> DataList => _dataList;

    public SCharacter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SCharacter Get(int key) => _dataMap[key];
    public SCharacter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

