
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum TCharacterID
    {
        /// <summary>
        /// 佩可莉姆
        /// </summary>
        PeiKeLiMu = 0,
        /// <summary>
        /// 草野优衣
        /// </summary>
        CaoYeYouYi = 1,
    }

} 

