
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TSkill
{
    private readonly System.Collections.Generic.Dictionary<int, SSkill> _dataMap;
    private readonly System.Collections.Generic.List<SSkill> _dataList;
    
    public TSkill(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SSkill>();
        _dataList = new System.Collections.Generic.List<SSkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SSkill _v;
            _v = SSkill.DeserializeSSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<SSkill> DataList => _dataList;

    public SSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SSkill Get(int key) => _dataMap[key];
    public SSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

